const measures=[
  {id:'brixUrine',label:'Brix urinaire',why:'Estime la concentration globale des solutés urinaires. Son interprétation devient plus solide lorsqu’elle évolue dans le même sens que la densité.'},
  {id:'densityUrine',label:'Densité urinaire',why:'Renseigne sur la concentration des urines. Elle dépend de l’abreuvement, de la température, de l’heure et du statut physiologique.'},
  {id:'phUrine',label:'pH urinaire',why:'Reflète en partie l’équilibre acido-basique et minéral. La valeur attendue varie selon la catégorie et les objectifs alimentaires.'},
  {id:'redoxUrine',label:'Redox urinaire',why:'Indicateur d’orientation du terrain oxydatif/réducteur, très sensible au protocole, au délai de lecture et à l’étalonnage.'},
  {id:'phFeces',label:'pH des bouses',why:'Oriente sur les fermentations digestives. Il doit être lu avec la consistance, les grains, les fibres et le contexte de ration.'},
  {id:'redoxFeces',label:'Redox des bouses',why:'Complète le pH des bouses pour caractériser la dynamique digestive et la cohérence du profil fermentaire.'},
  {id:'glycemia',label:'Glycémie sanguine',why:'Indicateur ponctuel de disponibilité énergétique. Le stress, la prise alimentaire et le délai entre prélèvement et lecture peuvent modifier le résultat.'},
  {id:'bohBlood',label:'BOH sanguin',why:'Le β-hydroxybutyrate augmente lorsque l’animal mobilise davantage ses réserves graisseuses. Il s’interprète avec la glycémie, l’ingestion, l’état corporel et le stade physiologique.'}
];
const contexts=['Chaleur','Changement de ration','Transition alimentaire','Baisse de production','Amaigrissement','Diarrhées','Bouses irrégulières','Eau douteuse','Accès à l’eau limité','Tri de ration','Fourrage nouveau','Stress ou compétition','Fin de gestation','Début de lactation','Baisse d’ingestion'];
const labels={low:'Bas',normal:'Normal',high:'Haut',na:'Non mesuré'};
const fiveMInfo={
  'Matière':'Ce qui entre dans le système : eau, fourrages, concentrés, minéraux, qualité sanitaire, équilibre énergie–azote et fibres efficaces.',
  'Milieu':'Conditions dans lesquelles vivent les animaux : chaleur, humidité, ventilation, densité, confort, accès à l’auge et à l’eau.',
  'Méthode':'Organisation des pratiques : transition, horaires, fréquence de distribution, protocole de prélèvement, suivi et contrôle des résultats.',
  'Matériel':'Équipements pouvant modifier l’exposition ou la mesure : abreuvoirs, mélangeuse, auge, appareils de mesure, étalonnage et entretien.',
  'Main-d’œuvre':'Régularité de l’observation et des gestes : repousse, nettoyage, détection des animaux à risque, respect du protocole et transmission des consignes.'
};
let currentResult=null; let deferredPrompt=null;
const measureGrid=document.getElementById('measureGrid');
measures.forEach(m=>{
  const row=document.createElement('div'); row.className='measure-row';
  row.innerHTML=`<div class="measure-head"><span class="measure-name">${m.label}</span><button class="info-btn" type="button" aria-label="Comprendre ${m.label}">?</button></div><div class="measure-help hidden">${m.why}</div><div class="segmented">${['low','normal','high','na'].map(v=>`<input type="radio" id="${m.id}-${v}" name="${m.id}" value="${v}" ${v==='na'?'checked':''}><label for="${m.id}-${v}">${labels[v]}</label>`).join('')}</div>`;
  row.querySelector('.info-btn').onclick=()=>row.querySelector('.measure-help').classList.toggle('hidden');
  measureGrid.appendChild(row);
});
const contextGrid=document.getElementById('contextGrid');
contexts.forEach((c,i)=>{const w=document.createElement('span');w.className='chip';w.innerHTML=`<input type="checkbox" id="ctx-${i}" value="${c}"><label for="ctx-${i}">${c}</label>`;contextGrid.appendChild(w)});
document.getElementById('visitDate').value=new Date().toISOString().slice(0,10);
function getFormData(){const values={};measures.forEach(m=>values[m.id]=document.querySelector(`input[name="${m.id}"]:checked`).value);return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),createdAt:new Date().toISOString(),farm:document.getElementById('farm').value.trim()||'Élevage non renseigné',visitDate:document.getElementById('visitDate').value,species:document.getElementById('species').value,category:document.getElementById('category').value.trim(),animalCount:document.getElementById('animalCount').value,reason:document.getElementById('reason').value.trim(),notes:document.getElementById('notes').value.trim(),contexts:[...document.querySelectorAll('#contextGrid input:checked')].map(x=>x.value),values}}
const is=(d,k,v)=>d.values[k]===v,has=(d,c)=>d.contexts.includes(c);
function addHyp(list,title,score,reasons,explanation,checks,actions,m){list.push({title,score,reasons,explanation,checks,actions,m})}
function analyse(d){
  const h=[],measured=Object.values(d.values).filter(v=>v!=='na').length;
  if(measured<2)addHyp(h,'Données insuffisantes pour une analyse croisée',25,['Moins de deux indicateurs renseignés.'],'Une valeur isolée décrit un instant mais ne permet pas de distinguer une variation biologique, un problème de prélèvement ou une tendance réelle du lot.',['Mesurer plusieurs animaux représentatifs','Associer au moins deux indicateurs cohérents'],['Compléter les données avant de conclure'],{Méthode:35});
  if(is(d,'brixUrine','high')&&is(d,'densityUrine','high'))addHyp(h,'Urines concentrées : abreuvement et pertes hydriques à explorer',88,['Brix urinaire haut','Densité urinaire haute',...(has(d,'Chaleur')?['Chaleur signalée']:[]),...(has(d,'Accès à l’eau limité')?['Accès à l’eau limité']:[])],'Le Brix et la densité décrivent tous deux la concentration urinaire. Leur hausse conjointe renforce l’hypothèse d’urines concentrées. Cela peut accompagner une consommation d’eau insuffisante, des pertes hydriques accrues, de la compétition ou une mesure faite à un moment particulier de la journée.',['Débit et nombre d’abreuvoirs','Propreté et accessibilité de l’eau','Répéter à un autre horaire'],['Sécuriser l’accès à l’eau','Corriger rapidement les défauts d’abreuvement'],{Matière:88,Milieu:75,Matériel:78,Méthode:45,'Main-d’œuvre':30});
  if(is(d,'brixUrine','low')&&is(d,'densityUrine','low'))addHyp(h,'Urines très diluées : profil à recontrôler',66,['Brix bas','Densité basse'],'La concordance des deux indicateurs évoque une urine peu concentrée. Elle peut être physiologique après une forte prise d’eau, mais doit aussi faire vérifier les conditions de prélèvement et la représentativité du lot.',['Heure de prélèvement','Consommation d’eau récente','Recontrôle sur plusieurs animaux'],['Documenter le protocole','Éviter une conclusion sur un seul prélèvement'],{Méthode:70,Matière:42,Milieu:25});
  if(is(d,'glycemia','low')&&is(d,'bohBlood','high'))addHyp(h,'Déficit énergétique et mobilisation des réserves à explorer',92,['Glycémie basse','BOH sanguin haut',...(has(d,'Début de lactation')?['Début de lactation']:[]),...(has(d,'Fin de gestation')?['Fin de gestation']:[]),...(has(d,'Baisse d’ingestion')?['Baisse d’ingestion']:[])],'Une glycémie basse suggère une disponibilité limitée en glucose, tandis qu’un BOH élevé témoigne d’une mobilisation accrue des graisses. Leur association est particulièrement évocatrice d’un bilan énergétique négatif, à confirmer selon l’espèce et le stade physiologique.',['État corporel et évolution du poids','Ingestion réelle et refus','Qualité énergétique de la ration','Signes cliniques et production'],['Sécuriser l’ingestion','Faire réévaluer la ration et les animaux à risque'],{Matière:95,Méthode:76,Milieu:45,'Main-d’œuvre':50});
  if(is(d,'glycemia','low')&&is(d,'bohBlood','normal'))addHyp(h,'Disponibilité énergétique basse sans forte cétogenèse détectée',72,['Glycémie basse','BOH normal'],'La disponibilité immédiate en glucose paraît basse, mais le BOH ne signale pas une mobilisation lipidique marquée au moment de la mesure. Cela peut correspondre à une prise alimentaire récente insuffisante, un stade physiologique particulier ou un résultat ponctuel.',['Moment du dernier repas','Répéter sur plusieurs animaux','Ingestion, état corporel et production'],['Surveiller les lots à besoins élevés','Vérifier la régularité des apports'],{Matière:80,Méthode:62});
  if(is(d,'glycemia','normal')&&is(d,'bohBlood','high'))addHyp(h,'Mobilisation des réserves malgré une glycémie conservée',78,['Glycémie normale','BOH haut'],'La glycémie peut rester dans la plage attendue alors que l’animal mobilise déjà ses réserves pour la maintenir. Le BOH élevé signale alors un effort métabolique qui mérite d’être rapproché de l’ingestion, de l’état corporel et du stade physiologique.',['État corporel','Baisse d’ingestion','Stade physiologique','Contrôle répété du BOH'],['Identifier les animaux à risque','Réévaluer densité énergétique et accès à l’auge'],{Matière:88,Méthode:68,Milieu:35});
  if(is(d,'glycemia','high'))addHyp(h,'Glycémie haute : stress, prise alimentaire ou contexte métabolique à vérifier',60,['Glycémie haute'],'Une glycémie élevée est moins spécifique : elle peut varier avec le stress de contention, le moment du repas, la méthode de prélèvement ou un trouble métabolique. Elle ne doit donc pas être interprétée seule.',['Stress de contention','Délai de lecture','Moment du repas','Répétition de la mesure'],['Standardiser le prélèvement','Confronter au BOH et au contexte clinique'],{Méthode:72,'Main-d’œuvre':48,Matière:40});
  if(is(d,'phFeces','low')&&(is(d,'redoxFeces','high')||has(d,'Transition alimentaire')||has(d,'Changement de ration')))addHyp(h,'Fermentations rapides / ration fermentescible à explorer',84,['pH des bouses bas',...(is(d,'redoxFeces','high')?['Redox des bouses haut']:[]),...(has(d,'Transition alimentaire')?['Transition en cours']:[])],'Un pH fécal bas traduit une acidification des contenus digestifs distaux. Associé à un Redox haut ou à une transition, il peut refléter l’arrivée d’une quantité importante de substrats fermentescibles insuffisamment valorisés en amont.',['Particules et grains dans les bouses','Tri de ration','Fibres efficaces','Amidon et sucres','Rumination'],['Sécuriser la transition','Revoir la structure et l’homogénéité de ration'],{Matière:92,Méthode:84,Matériel:45,'Main-d’œuvre':38});
  if(is(d,'phFeces','high')&&is(d,'redoxFeces','low'))addHyp(h,'Digestion lente ou incomplète à explorer',72,['pH des bouses haut','Redox des bouses bas'],'Cette combinaison peut accompagner une fermentation moins intense ou une valorisation digestive insuffisante. Elle doit être confrontée à l’ingestion, à la qualité des fourrages et à la présence de particules non digérées.',['Fibres et grains non digérés','Ingestibilité des fourrages','Niveau d’ingestion','Rumination'],['Vérifier la structure de ration','Contrôler mélange et distribution'],{Matière:84,Méthode:60,Matériel:46});
  if(is(d,'phUrine','low')&&(is(d,'phFeces','low')||is(d,'redoxUrine','high')))addHyp(h,'Profil acide concordant à interpréter selon la catégorie',78,['pH urinaire bas',...(is(d,'phFeces','low')?['pH des bouses bas']:[]),...(is(d,'redoxUrine','high')?['Redox urinaire haut']:[])],'Le pH urinaire ne se juge pas de la même manière chez une femelle en préparation au vêlage, un animal en lactation ou un jeune. La concordance avec d’autres indicateurs renforce l’intérêt du profil, mais la référence propre à la catégorie reste indispensable.',['Stade physiologique précis','Ration minérale','Équilibre alimentaire','Signes cliniques'],['Comparer aux références du lot','Faire confirmer avant correction de ration'],{Matière:88,Méthode:62});
  if(is(d,'phUrine','high')&&is(d,'phFeces','high'))addHyp(h,'Profil alcalin concordant à contextualiser',70,['pH urinaire haut','pH des bouses haut'],'Deux pH orientés vers le haut peuvent refléter le contexte alimentaire et minéral, mais aussi la catégorie animale ou les conditions de conservation du prélèvement. La cohérence doit être confirmée par le lot et les performances.',['Catégorie et stade','Ration et minéraux','Conditions de prélèvement'],['Recontrôler avant modification','Comparer aux objectifs du lot'],{Matière:77,Méthode:58});
  if((is(d,'redoxUrine','high')&&is(d,'redoxFeces','high'))||(is(d,'redoxUrine','low')&&is(d,'redoxFeces','low')))addHyp(h,'Profil Redox concordant entre urine et bouses',64,['Redox urinaire et fécal dans le même sens'],'La concordance entre deux matrices différentes rend le signal plus intéressant, mais le Redox est très sensible à l’air, au délai de lecture, à la température et à l’étalonnage. Il faut d’abord sécuriser la qualité technique de la mesure.',['Étalonnage','Délai prélèvement–lecture','Température','Répétition sur plusieurs animaux'],['Standardiser le protocole','Interpréter avec pH, ration et clinique'],{Méthode:82,Matériel:68,Matière:45});
  const discord=(is(d,'brixUrine','high')&&is(d,'densityUrine','low'))||(is(d,'brixUrine','low')&&is(d,'densityUrine','high'));
  if(discord)addHyp(h,'Discordance Brix–densité : mesure à vérifier',82,['Brix et densité évoluent en sens opposés'],'Comme ces deux mesures décrivent la concentration urinaire, une opposition franche suggère d’abord un problème de mesure, d’étalonnage, de lecture ou de contamination du prélèvement plutôt qu’une interprétation biologique immédiate.',['Reprendre sur le même prélèvement','Nettoyer et étalonner','Contrôler température et délai'],['Ne pas interpréter avant vérification','Standardiser le prélèvement'],{Méthode:94,Matériel:90});
  if(has(d,'Eau douteuse'))addHyp(h,'Qualité de l’eau à contrôler',62,['Qualité d’eau douteuse signalée'],'Même avec un volume disponible, une eau sale, odorante, chaude ou de qualité physico-chimique médiocre peut diminuer la consommation et dégrader les performances.',['Aspect et odeur','Analyse si nécessaire','Canalisations et nettoyage'],['Nettoyer les points d’eau','Programmer un contrôle'],{Matière:80,Matériel:64,Milieu:50});
  if(has(d,'Tri de ration'))addHyp(h,'Tri de ration susceptible d’expliquer l’hétérogénéité',60,['Tri observé'],'Le tri crée des ingestions différentes entre animaux et au cours de la journée. Le lot peut alors présenter des profils biologiques hétérogènes malgré une ration théorique correcte.',['Distribué versus refus','Longueur des fibres','Homogénéité et humidité','Accès à l’auge'],['Limiter le tri','Revoir mélange et repousse'],{Matière:72,Matériel:68,Méthode:78,'Main-d’œuvre':48});
  h.sort((a,b)=>b.score-a.score);
  const allNormal=measured>0&&Object.values(d.values).filter(v=>v!=='na').every(v=>v==='normal');
  if(allNormal)addHyp(h,'Profil déclaré globalement dans les normes',45,['Toutes les mesures renseignées sont normales.'],'L’absence d’anomalie sur ces indicateurs est rassurante, mais n’exclut pas un problème non mesuré. La représentativité des animaux et l’adaptation des références restent déterminantes.',['Références adaptées au lot','Observations cliniques et zootechniques'],['Poursuivre la surveillance','Comparer à la prochaine visite'],{Méthode:25,Matière:20});
  const five={Matière:0,Milieu:0,Méthode:0,Matériel:0,'Main-d’œuvre':0},fiveReasons={Matière:[],Milieu:[],Méthode:[],Matériel:[],'Main-d’œuvre':[]};
  h.forEach(x=>Object.entries(x.m||{}).forEach(([k,v])=>{if(v>(five[k]||0))five[k]=v;if(v>=45)fiveReasons[k].push(x.title)}));
  const coherence=discord?'Mesures discordantes':measured<2?'Données insuffisantes':h.some(x=>x.score>=80)?'Concordance forte':'Orientation modérée';
  return{data:d,hypotheses:h.slice(0,6),five,fiveReasons,coherence,measured};
}
function renderResult(r){
  currentResult=r;const{hypotheses:h,five,fiveReasons,coherence,measured}=r;
  document.getElementById('resultTitle').textContent=h[0]?.title||'Aucune orientation majeure';
  document.getElementById('resultSummary').textContent=`${measured} indicateur(s) renseigné(s). ${h.length?`${h.length} piste(s) classée(s) selon leur concordance.`:'Aucune combinaison notable détectée.'}`;
  const badge=document.getElementById('coherenceBadge');badge.textContent=coherence;badge.className='badge '+(coherence==='Concordance forte'?'bad':coherence==='Orientation modérée'?'warn':coherence==='Mesures discordantes'?'bad':'warn');
  document.getElementById('hypotheses').innerHTML=h.length?h.map((x,i)=>`<article class="hypothesis"><button class="hypothesis-toggle" type="button" aria-expanded="${i===0}"><span><strong>${x.title}</strong><small>${x.score>=80?'Concordance forte':x.score>=60?'À explorer':'Faible'}</small></span><span>⌄</span></button><div class="hypothesis-detail ${i===0?'':'hidden'}"><h3>Pourquoi cette piste apparaît</h3><p>${x.explanation}</p><h3>Éléments utilisés</h3><ul class="reason-list">${x.reasons.map(y=>`<li>${y}</li>`).join('')}</ul><h3>Ce qui permettrait de confirmer ou d’écarter</h3><ul class="reason-list">${x.checks.map(y=>`<li>${y}</li>`).join('')}</ul></div></article>`).join(''):'<p class="muted">Aucune orientation notable.</p>';
  document.querySelectorAll('.hypothesis-toggle').forEach(b=>b.onclick=()=>{const d=b.nextElementSibling;d.classList.toggle('hidden');b.setAttribute('aria-expanded',String(!d.classList.contains('hidden')))});
  document.getElementById('fiveM').innerHTML=Object.entries(five).map(([k,v])=>`<article class="m-card"><button class="m-toggle" type="button"><div class="m-row"><strong>${k}</strong><div class="m-track"><div class="m-fill" style="width:${v}%"></div></div><span class="m-score">${v}%</span></div><span class="m-open">Voir le détail</span></button><div class="m-detail hidden"><p>${fiveMInfo[k]}</p><strong>Pourquoi cet axe ressort ici :</strong>${fiveReasons[k]?.length?`<ul>${[...new Set(fiveReasons[k])].map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p class="muted">Aucun élément majeur détecté dans cet axe.</p>'}</div></article>`).join('');
  document.querySelectorAll('.m-toggle').forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('hidden'));
  const checks=[...new Set(h.flatMap(x=>x.checks))],acts=[...new Set(h.flatMap(x=>x.actions))];
  document.getElementById('checks').innerHTML=checks.length?`<ul class="check-list">${checks.map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p class="muted">Compléter les mesures et les observations.</p>';
  document.getElementById('actionsPlan').innerHTML=acts.length?`<ol class="action-list">${acts.map(x=>`<li>${x}</li>`).join('')}</ol>`:'<p class="muted">Aucune action spécifique proposée.</p>';
  document.getElementById('results').classList.remove('hidden');setTimeout(()=>document.getElementById('results').scrollIntoView({behavior:'smooth',block:'start'}),50);
}
document.getElementById('analysisForm').addEventListener('submit',e=>{e.preventDefault();renderResult(analyse(getFormData()))});
document.getElementById('resetBtn').addEventListener('click',()=>{document.getElementById('analysisForm').reset();document.getElementById('visitDate').value=new Date().toISOString().slice(0,10);measures.forEach(m=>document.getElementById(`${m.id}-na`).checked=true);document.getElementById('results').classList.add('hidden');currentResult=null});
document.getElementById('printBtn').addEventListener('click',()=>window.print());
function history(){return JSON.parse(localStorage.getItem('mvet-history')||'[]')}function saveHistory(v){localStorage.setItem('mvet-history',JSON.stringify(v));renderHistory()}
document.getElementById('saveBtn').addEventListener('click',()=>{if(!currentResult)return;const h=history();h.unshift(currentResult);saveHistory(h.slice(0,100));alert('Visite enregistrée sur cet appareil.')});
function renderHistory(){const list=document.getElementById('historyList'),h=history();list.innerHTML='';if(!h.length){list.innerHTML='<p class="muted">Aucune visite enregistrée.</p>';return}const t=document.getElementById('historyTemplate');h.forEach((item,i)=>{const n=t.content.cloneNode(true);n.querySelector('.h-farm').textContent=item.data.farm;n.querySelector('.h-meta').textContent=`${item.data.visitDate||''} · ${item.data.species}${item.data.category?' · '+item.data.category:''}`;n.querySelector('.h-title').textContent=item.hypotheses[0]?.title||'Analyse enregistrée';n.querySelector('.h-open').onclick=()=>{switchScreen('analyse');renderResult(item)};n.querySelector('.h-delete').onclick=()=>{const a=history();a.splice(i,1);saveHistory(a)};list.appendChild(n)})}
document.getElementById('clearHistoryBtn').addEventListener('click',()=>{if(confirm('Supprimer tout l’historique de cet appareil ?'))saveHistory([])});
function switchScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.screen===name));document.getElementById(`screen-${name}`).classList.add('active');if(name==='history')renderHistory();window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tab').forEach(t=>t.addEventListener('click',()=>switchScreen(t.dataset.screen)));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});
document.getElementById('installBtn').addEventListener('click',async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installBtn').classList.add('hidden')});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderHistory();
