const measures=[
{id:'brixUrine',label:'Brix urinaire',why:'Apprécie la concentration globale des solutés urinaires. Il gagne en valeur quand il concorde avec la densité urinaire.',quick:{low:'Urines peu concentrées',normal:'Concentration attendue',high:'Urines concentrées'}},
{id:'densityUrine',label:'Densité urinaire',why:'Renseigne sur la capacité de concentration des urines et dépend de l’abreuvement, de la chaleur, de l’heure et du stade physiologique.',quick:{low:'Urines diluées',normal:'Concentration attendue',high:'Urines concentrées'}},
{id:'phUrine',label:'pH urinaire',why:'Oriente sur l’équilibre acido-basique et minéral. Il ne s’interprète qu’avec la catégorie animale, la ration et le protocole.',quick:{low:'Urines acides',normal:'pH dans la plage attendue',high:'Urines alcalines'}},
{id:'redoxUrine',label:'Redox urinaire',why:'Indicateur d’orientation du terrain oxydatif/réducteur, très sensible au temps de lecture, à l’air, à la température et à l’étalonnage.',quick:{low:'Milieu plus réducteur',normal:'Équilibre Redox attendu',high:'Milieu plus oxydant'}},
{id:'phFeces',label:'pH des bouses',why:'Oriente sur la fermentation digestive distale. À lire avec la consistance, les grains, les fibres, le tri et les transitions.',quick:{low:'Bouses acides',normal:'Fermentation compatible',high:'Bouses alcalines'}},
{id:'redoxFeces',label:'Redox des bouses',why:'Complète le pH des bouses pour apprécier la dynamique fermentaire et la cohérence du profil digestif.',quick:{low:'Milieu très réducteur',normal:'Équilibre Redox attendu',high:'Milieu plus oxydant'}},
{id:'glycemia',label:'Glycémie sanguine',why:'Indicateur ponctuel de disponibilité du glucose. Le stress, la prise alimentaire et le délai de lecture peuvent fortement le modifier.',quick:{low:'Disponibilité énergétique basse',normal:'Disponibilité énergétique conservée',high:'Hyperglycémie à contextualiser'}},
{id:'bohBlood',label:'BOH sanguin',why:'Le β-hydroxybutyrate augmente lors de mobilisation des réserves graisseuses. Il se croise avec glycémie, ingestion, état corporel et stade.',quick:{low:'Faible mobilisation lipidique',normal:'Mobilisation dans la plage attendue',high:'Mobilisation des graisses importante'}},
{id:'ureaBlood',label:'Urée sanguine',why:'Oriente sur l’équilibre entre apports azotés, énergie fermentescible et utilisation de l’azote. Elle dépend aussi de l’hydratation et de la fonction rénale.',quick:{low:'Azote disponible ou valorisé insuffisant',normal:'Équilibre azote-énergie compatible',high:'Excès d’azote ou défaut de valorisation'}},
{id:'phBlood',label:'pH sanguin',why:'Mesure majeure de l’équilibre acido-basique. Une anomalie réelle doit être confirmée rapidement avec un prélèvement adapté et le contexte clinique.',quick:{low:'Acidémie possible',normal:'Équilibre acido-basique conservé',high:'Alcalémie possible'}}
];
const contexts=['Chaleur / canicule','Changement de ration','Transition alimentaire','Baisse de production','Amaigrissement','Diarrhées','Bouses irrégulières','Eau douteuse','Accès à l’eau limité','Tri de ration','Fourrage nouveau','Stress / compétition','Fin de gestation','Début de lactation','Baisse d’ingestion','Ration riche en concentrés','Ration riche en azote','Jeunes animaux'];
const labels={low:'Bas',normal:'Normal',high:'Haut',na:'Non mesuré'};
const fiveMInfo={
'Matière':{desc:'Eau, fourrages, concentrés, minéraux, énergie, azote, fibres et qualité sanitaire.',controls:['Analyser la ration réellement ingérée','Comparer distribué, refus et tri','Contrôler eau et minéralisation'],effects:['Déséquilibre énergétique ou azoté','Fermentations anormales','Mobilisation des réserves']},
'Milieu':{desc:'Chaleur, ventilation, confort, densité, compétition et accessibilité de l’eau ou de l’auge.',controls:['Observer les animaux aux heures critiques','Mesurer débit et accessibilité de l’eau','Évaluer confort et compétition'],effects:['Baisse d’ingestion','Pertes hydriques','Stress et hétérogénéité du lot']},
'Méthode':{desc:'Transitions, fréquence de distribution, horaires, protocole de prélèvement, suivi et recontrôle.',controls:['Documenter heure et conditions de prélèvement','Vérifier progressivité des transitions','Comparer plusieurs animaux et plusieurs dates'],effects:['Résultats peu représentatifs','Variabilité digestive','Retard de détection']},
'Matériel':{desc:'Abreuvoirs, mélangeuse, auge, appareils de mesure, entretien, nettoyage et étalonnage.',controls:['Contrôler débit des abreuvoirs','Vérifier homogénéité de mélange','Nettoyer et étalonner les appareils'],effects:['Accès insuffisant','Ration hétérogène','Erreur ou dérive de mesure']},
'Main-d’œuvre':{desc:'Régularité des pratiques, observation, repousse, détection des animaux à risque et transmission des consignes.',controls:['Vérifier la régularité des gestes','Formaliser les consignes','Identifier les animaux sentinelles'],effects:['Détection tardive','Variabilité entre jours','Mesures correctives incomplètes']}
};
let currentResult=null,deferredPrompt=null;
const measureGrid=document.getElementById('measureGrid');
measures.forEach(m=>{const row=document.createElement('div');row.className='measure-row';row.innerHTML=`<div class="measure-head"><span class="measure-name">${m.label}</span><button class="info-btn" type="button">?</button></div><div class="measure-help hidden">${m.why}</div><div class="segmented">${['low','normal','high','na'].map(v=>`<input type="radio" id="${m.id}-${v}" name="${m.id}" value="${v}" ${v==='na'?'checked':''}><label for="${m.id}-${v}">${labels[v]}</label>`).join('')}</div>`;row.querySelector('.info-btn').onclick=()=>row.querySelector('.measure-help').classList.toggle('hidden');measureGrid.appendChild(row)});
const contextGrid=document.getElementById('contextGrid');contexts.forEach((c,i)=>{const w=document.createElement('span');w.className='chip';w.innerHTML=`<input type="checkbox" id="ctx-${i}" value="${c}"><label for="ctx-${i}">${c}</label>`;contextGrid.appendChild(w)});
document.getElementById('visitDate').value=new Date().toISOString().slice(0,10);
function getFormData(){const values={};measures.forEach(m=>values[m.id]=document.querySelector(`input[name="${m.id}"]:checked`).value);return{id:crypto.randomUUID?.()||String(Date.now()),createdAt:new Date().toISOString(),farm:document.getElementById('farm').value.trim()||'Élevage non renseigné',visitDate:document.getElementById('visitDate').value,species:document.getElementById('species').value,category:document.getElementById('category').value.trim(),animalCount:document.getElementById('animalCount').value,reason:document.getElementById('reason').value.trim(),notes:document.getElementById('notes').value.trim(),contexts:[...document.querySelectorAll('#contextGrid input:checked')].map(x=>x.value),values}}
const is=(d,k,v)=>d.values[k]===v,has=(d,c)=>d.contexts.includes(c);
function add(list,title,score,reasons,mechanism,consequences,checks,actions,m,limits=[]){list.push({title,score,reasons,mechanism,consequences,checks,actions,m,limits})}
function analyse(d){const h=[],measured=Object.values(d.values).filter(v=>v!=='na').length;
if(measured<3)add(h,'Données encore limitées',35,['Moins de trois indicateurs renseignés'],'Une mesure isolée peut varier avec l’animal, l’heure ou le prélèvement. Le croisement de plusieurs matrices est nécessaire pour distinguer une tendance du lot d’un résultat ponctuel.',[],['Mesurer plusieurs animaux représentatifs','Ajouter au moins un indicateur digestif, urinaire ou sanguin'],['Compléter les données avant toute correction'],{Méthode:55},['La fiabilité restera faible tant que peu de paramètres sont renseignés.']);
if(is(d,'brixUrine','high')&&is(d,'densityUrine','high'))add(h,'Concentration urinaire élevée : apport hydrique ou pertes à vérifier',88,['Brix urinaire haut','Densité urinaire haute',...(has(d,'Chaleur / canicule')?['Chaleur signalée']:[]),...(has(d,'Accès à l’eau limité')?['Accès à l’eau limité']:[])],'Les deux indicateurs évoluent dans le même sens et traduisent une réduction de la part d’eau dans les urines. Cela peut résulter d’une consommation insuffisante, de pertes liées à la chaleur, d’une compétition ou d’une forte concentration de solutés.',['Baisse d’ingestion','Moindre production','Risque de sous-abreuvement du lot'],['Débit, nombre et propreté des abreuvoirs','Accessibilité aux heures de pointe','Recontrôle à un autre horaire'],['Sécuriser immédiatement l’accès à l’eau','Corriger les défauts de débit ou de compétition'],{Matière:85,Milieu:82,Matériel:80,Méthode:45},['Une forte ingestion de sels ou un prélèvement matinal peut aussi concentrer les urines.']);
if(is(d,'brixUrine','low')&&is(d,'densityUrine','low'))add(h,'Urines très diluées : prise d’eau récente ou profil à recontrôler',65,['Brix bas','Densité basse'],'La baisse concordante indique une faible concentration des urines. Elle peut être physiologique après une prise d’eau importante, mais aussi traduire un prélèvement peu représentatif.',[],['Heure de prélèvement','Prise d’eau récente','Répéter sur plusieurs animaux'],['Standardiser le protocole'],{Méthode:76,Matière:42},['Ne pas conclure sur une mesure unique.']);
if(is(d,'glycemia','low')&&is(d,'bohBlood','high'))add(h,'Bilan énergétique négatif avec mobilisation des réserves',94,['Glycémie basse','BOH haut',...(has(d,'Début de lactation')?['Début de lactation']:[]),...(has(d,'Baisse d’ingestion')?['Baisse d’ingestion']:[])],'Le glucose disponible est bas alors que le BOH montre que les graisses corporelles sont mobilisées pour couvrir les besoins. Cette association est très cohérente avec un déficit entre besoins et énergie réellement ingérée.',['Amaigrissement','Baisse de production','Risque accru de troubles métaboliques et de reproduction'],['Ingestion réelle et refus','État corporel et évolution du poids','Densité énergétique de la ration','Animaux récemment vêlés'],['Sécuriser l’ingestion','Identifier les animaux à risque','Faire réévaluer la ration'],{Matière:97,Méthode:78,Milieu:48,'Main-d’œuvre':55},['Interpréter selon l’espèce, le stade physiologique et le délai prélèvement-lecture.']);
if(is(d,'glycemia','normal')&&is(d,'bohBlood','high'))add(h,'Mobilisation des réserves malgré une glycémie maintenue',82,['Glycémie normale','BOH haut'],'L’organisme parvient encore à maintenir la glycémie, mais au prix d’une mobilisation lipidique accrue. Le BOH peut donc révéler plus tôt l’effort métabolique que la glycémie.', ['Risque de perte d’état','Dégradation possible des performances'],['État corporel','Ingestion et refus','Contrôle répété du BOH'],['Surveiller les lots à forts besoins','Revoir densité énergétique et accès à l’auge'],{Matière:90,Méthode:70});
if(is(d,'glycemia','low')&&is(d,'bohBlood','normal'))add(h,'Disponibilité énergétique basse sans cétogenèse marquée',72,['Glycémie basse','BOH normal'],'La disponibilité immédiate en glucose paraît faible, mais la mobilisation des graisses n’est pas élevée au moment du contrôle. Cela peut être ponctuel ou lié au repas, au stress ou au stade physiologique.',[],['Moment du repas','Répéter sur plusieurs animaux','Production et ingestion'],['Surveiller les animaux à besoins élevés'],{Matière:76,Méthode:68});
if(is(d,'ureaBlood','high'))add(h,'Urée sanguine élevée : excès d’azote ou énergie fermentescible insuffisante',80,['Urée sanguine haute',...(has(d,'Ration riche en azote')?['Ration riche en azote signalée']:[])],'L’azote ruminal non capté par les microorganismes est transformé en ammoniac puis en urée. Une urée haute peut donc traduire trop d’azote dégradable, un manque d’énergie synchronisée pour le valoriser, ou une concentration liée à l’hydratation.',['Gaspillage azoté','Coût alimentaire inutile','Possibles effets sur performances et reproduction'],['Teneur en MAT et azote soluble','Synchronisation énergie-azote','Hydratation','Comparer avec production et ration'],['Rééquilibrer l’azote et l’énergie fermentescible','Ne pas diminuer les protéines sans analyse de ration'],{Matière:95,Méthode:72},['La fonction rénale et l’hydratation influencent aussi l’urée.']);
if(is(d,'ureaBlood','low'))add(h,'Urée sanguine basse : apport azoté ou valorisation ruminale à examiner',72,['Urée sanguine basse'],'Une urée basse peut accompagner un apport protéique insuffisant, une faible ingestion, ou une utilisation très efficace de l’azote disponible. Elle doit être mise en regard de la production, de l’état corporel et de la ration.', ['Risque de limitation de la synthèse microbienne si l’apport est réellement insuffisant'],['Ingestion réelle','MAT de la ration','Production et état corporel','Qualité des fourrages'],['Vérifier la ration avant supplémentation'],{Matière:88,Méthode:58});
if(is(d,'ureaBlood','high')&&is(d,'glycemia','low'))add(h,'Désynchronisation énergie–azote probable',90,['Urée haute','Glycémie basse'],'L’azote paraît abondant alors que l’énergie disponible est limitée. Les microorganismes du rumen peuvent manquer d’énergie pour incorporer l’ammoniac, qui est alors converti en urée.',['Mauvaise efficacité alimentaire','Pertes azotées','Déficit énergétique persistant'],['Énergie fermentescible','Répartition des apports','Tri de ration','Ingestion'],['Revoir la synchronisation des apports'],{Matière:98,Méthode:82,Matériel:45});
if(is(d,'phBlood','low'))add(h,'Acidémie possible : situation à confirmer rapidement',92,['pH sanguin bas',...(is(d,'phUrine','low')?['pH urinaire bas']:[]),...(is(d,'phFeces','low')?['pH des bouses bas']:[])],'Le pH sanguin bas signifie que les mécanismes tampons ne maintiennent plus totalement l’équilibre. Selon le contexte, il peut s’agir d’une acidose métabolique, respiratoire ou d’une altération pré-analytique. Ce résultat est plus préoccupant qu’un simple pH urinaire ou fécal bas.',['Altération de l’état général','Baisse d’ingestion','Troubles métaboliques potentiellement urgents'],['Confirmer sur prélèvement adapté','Évaluer signes cliniques et respiration','Bicarbonates/gaz sanguins si disponibles','Avis vétérinaire'],['Ne pas corriger la ration sur ce seul résultat','Faire confirmer rapidement si animal symptomatique'],{Matière:78,Méthode:82,Matériel:70},['Le contact avec l’air et le délai modifient fortement le pH sanguin.']);
if(is(d,'phBlood','high'))add(h,'Alcalémie possible : origine métabolique, respiratoire ou pré-analytique',88,['pH sanguin haut'],'Un pH sanguin élevé traduit une alcalémie possible. Elle peut être liée à des pertes acides, à la ventilation, à certains apports minéraux ou à un prélèvement mal conservé.', ['Déséquilibre électrolytique possible'],['Confirmer le prélèvement','Respiration et signes cliniques','Ration minérale et traitements'],['Demander confirmation vétérinaire si anomalie persistante'],{Matière:70,Méthode:82,Matériel:72});
if(is(d,'phFeces','low')&&(is(d,'redoxFeces','high')||has(d,'Ration riche en concentrés')||has(d,'Transition alimentaire')))add(h,'Fermentation digestive rapide avec excès de substrats fermentescibles',86,['pH des bouses bas',...(is(d,'redoxFeces','high')?['Redox des bouses haut']:[]),...(has(d,'Ration riche en concentrés')?['Ration riche en concentrés']:[])],'Des glucides fermentescibles atteignent les compartiments digestifs distaux et y produisent des acides. Cela peut arriver quand la ration est trop rapidement fermentescible, mal synchronisée ou insuffisamment structurée.', ['Bouses instables','Valorisation alimentaire réduite','Risque de baisse d’ingestion ou de production'],['Grains et fibres dans les bouses','Longueur des fibres','Tri et refus','Progressivité de la transition'],['Revoir amidon, fibres efficaces et transition','Contrôler homogénéité du mélange'],{Matière:96,Méthode:84,Matériel:58});
if(is(d,'phUrine','low')&&is(d,'phBlood','normal'))add(h,'Urines acides avec équilibre sanguin conservé',70,['pH urinaire bas','pH sanguin normal'],'L’organisme maintient le pH sanguin, notamment en éliminant une charge acide par les reins. Le pH urinaire bas n’est donc pas synonyme à lui seul d’acidose sanguine : il peut refléter la ration, la minéralisation ou un mécanisme compensatoire normal.',[],['Objectifs selon catégorie','Ration minérale','Répéter sur le lot'],['Interpréter selon les références de catégorie'],{Matière:76,Méthode:60});
if(is(d,'phUrine','low')&&is(d,'phFeces','low')&&d.values.phBlood==='na')add(h,'Charge acide alimentaire et fermentaire à explorer, sans preuve d’acidémie',82,['pH urinaire bas','pH des bouses bas'],'Les deux matrices vont dans le sens d’une acidification, mais elles renseignent des mécanismes différents. Les bouses orientent vers les fermentations digestives, tandis que les urines reflètent l’excrétion rénale et la ration minérale. Sans pH sanguin, on ne peut pas conclure à une acidose générale.', ['Risque de ration trop fermentescible ou mal tamponnée'],['pH sanguin si justifié','Fibres efficaces','Amidon et minéralisation'],['Contrôler la ration avant toute conclusion'],{Matière:92,Méthode:72});
const discord=(is(d,'brixUrine','high')&&is(d,'densityUrine','low'))||(is(d,'brixUrine','low')&&is(d,'densityUrine','high'));
if(discord)add(h,'Discordance Brix–densité : fiabilité technique à vérifier',91,['Brix et densité en sens opposés'],'Ces deux mesures décrivent la concentration urinaire. Une opposition franche fait d’abord suspecter température, étalonnage, contamination ou lecture avant une cause biologique.',[],['Reprendre sur le même prélèvement','Nettoyer et étalonner','Contrôler délai et température'],['Ne pas interpréter avant vérification'],{Méthode:98,Matériel:96});
if(has(d,'Tri de ration'))add(h,'Tri de ration : source probable d’hétérogénéité du lot',68,['Tri de ration observé'],'Les animaux et les moments de la journée ne reçoivent plus la même ration réellement ingérée. Des profils biologiques différents peuvent alors coexister malgré une formule théorique correcte.', ['Variabilité des bouses et performances','Animaux dominés plus exposés'],['Distribué versus refus','Longueur et humidité','Accès à l’auge'],['Limiter le tri','Revoir mélange et repousse'],{Matière:74,Méthode:84,Matériel:72,'Main-d’œuvre':58});
h.sort((a,b)=>b.score-a.score);
const five={Matière:0,Milieu:0,Méthode:0,Matériel:0,'Main-d’œuvre':0},fiveReasons={Matière:[],Milieu:[],Méthode:[],Matériel:[],'Main-d’œuvre':[]};h.forEach(x=>Object.entries(x.m||{}).forEach(([k,v])=>{five[k]=Math.max(five[k]||0,v);if(v>=45)fiveReasons[k].push(x.title)}));
const normalCount=Object.values(d.values).filter(v=>v==='normal').length, reliability=Math.min(100,Math.round(measured/measures.length*75)+(measured>=6?15:0)-(discord?25:0));
const coherence=discord?'Discordante':measured<3?'Faible':h[0]?.score>=85?'Forte':'Modérée';
const alert=h.some(x=>x.title.includes('Acidémie')||x.title.includes('Alcalémie'))?'Élevé':h[0]?.score>=85?'Modéré':'Faible';
return{data:d,hypotheses:h.slice(0,7),five,fiveReasons,coherence,measured,normalCount,reliability,alert};}
function renderResult(r){currentResult=r;const{data:d,hypotheses:h,five,fiveReasons,coherence,measured,reliability,alert}=r;
document.getElementById('resultTitle').textContent=h[0]?.title||'Aucune orientation majeure';document.getElementById('resultSummary').textContent=`${measured}/${measures.length} paramètres évalués. Les pistes ci-dessous sont classées selon la concordance entre mesures et contexte.`;
document.getElementById('coherenceBadge').textContent=coherence;document.getElementById('coherenceBadge').className='badge '+(coherence==='Forte'?'ok':coherence==='Discordante'?'bad':'warn');
document.getElementById('summaryCards').innerHTML=`<article><small>Cohérence globale</small><strong>${coherence}</strong><span>${coherence==='Forte'?'Les données vont majoritairement dans le même sens.':'Vérifier la représentativité et les discordances.'}</span></article><article><small>Profil principal</small><strong>${h[0]?.title||'Non déterminé'}</strong><span>${h[0]?.score||0}% de concordance indicative</span></article><article><small>Niveau d’alerte</small><strong>${alert}</strong><span>${alert==='Élevé'?'Confirmation rapide conseillée.':'Prioriser les contrôles terrain.'}</span></article><article><small>Fiabilité</small><strong>${reliability}%</strong><span>${measured}/${measures.length} paramètres renseignés</span></article>`;
document.getElementById('measureSummary').innerHTML=measures.filter(m=>d.values[m.id]!=='na').map(m=>`<tr><td>${m.label}</td><td><span class="state ${d.values[m.id]}">${labels[d.values[m.id]]}</span></td><td>${m.quick[d.values[m.id]]}</td></tr>`).join('')||'<tr><td colspan="3">Aucune mesure renseignée.</td></tr>';
document.getElementById('hypotheses').innerHTML=h.length?h.map((x,i)=>`<article class="hypothesis"><button class="hypothesis-toggle" type="button"><span class="rank">${i+1}</span><span class="hyp-title"><strong>${x.title}</strong><small>Concordance indicative : ${x.score}%</small></span><span>Voir le détail</span></button><div class="hypothesis-detail hidden"><h3>Mécanisme possible</h3><p>${x.mechanism}</p>${x.consequences.length?`<h3>Conséquences possibles</h3><ul>${x.consequences.map(y=>`<li>${y}</li>`).join('')}</ul>`:''}<h3>Éléments qui soutiennent cette piste</h3><ul>${x.reasons.map(y=>`<li>${y}</li>`).join('')}</ul><h3>À contrôler pour confirmer ou écarter</h3><ul>${x.checks.map(y=>`<li>${y}</li>`).join('')}</ul>${x.limits.length?`<h3>Limites d’interprétation</h3><ul>${x.limits.map(y=>`<li>${y}</li>`).join('')}</ul>`:''}</div></article>`).join(''):'<p>Aucune combinaison notable.</p>';
document.querySelectorAll('.hypothesis-toggle').forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('hidden'));
document.getElementById('fiveM').innerHTML=Object.entries(five).map(([k,v])=>`<article class="m-card"><button class="m-toggle" type="button"><strong>${k}</strong><span class="m-score">${v}%</span><div class="m-track"><div class="m-fill" style="width:${v}%"></div></div><small>Voir le détail</small></button><div class="m-detail hidden"><p>${fiveMInfo[k].desc}</p><h3>Pourquoi cet axe ressort</h3>${fiveReasons[k].length?`<ul>${[...new Set(fiveReasons[k])].map(x=>`<li>${x}</li>`).join('')}</ul>`:'<p>Aucun signal majeur.</p>'}<h3>Contrôles ciblés</h3><ul>${fiveMInfo[k].controls.map(x=>`<li>${x}</li>`).join('')}</ul><h3>Conséquences possibles</h3><ul>${fiveMInfo[k].effects.map(x=>`<li>${x}</li>`).join('')}</ul></div></article>`).join('');document.querySelectorAll('.m-toggle').forEach(b=>b.onclick=()=>b.nextElementSibling.classList.toggle('hidden'));
const checks=[...new Set(h.flatMap(x=>x.checks))].slice(0,12),acts=[...new Set(h.flatMap(x=>x.actions))].slice(0,8);document.getElementById('checks').innerHTML=checks.map(x=>`<label class="task"><input type="checkbox">${x}</label>`).join('')||'<p>Compléter les données.</p>';document.getElementById('actionsPlan').innerHTML=acts.length?`<ol>${acts.map(x=>`<li>${x}</li>`).join('')}</ol>`:'<p>Aucune action ciblée.</p>';document.getElementById('results').classList.remove('hidden');setTimeout(()=>document.getElementById('results').scrollIntoView({behavior:'smooth'}),50)}
document.getElementById('analysisForm').onsubmit=e=>{e.preventDefault();renderResult(analyse(getFormData()))};document.getElementById('resetBtn').onclick=()=>{document.getElementById('analysisForm').reset();document.getElementById('visitDate').value=new Date().toISOString().slice(0,10);measures.forEach(m=>document.getElementById(`${m.id}-na`).checked=true);document.getElementById('results').classList.add('hidden')};document.getElementById('printBtn').onclick=()=>window.print();
function history(){return JSON.parse(localStorage.getItem('mvet-history')||'[]')}function saveHistory(v){localStorage.setItem('mvet-history',JSON.stringify(v));renderHistory()}document.getElementById('saveBtn').onclick=()=>{if(!currentResult)return;const h=history();h.unshift(currentResult);saveHistory(h.slice(0,100));alert('Visite enregistrée.')};function renderHistory(){const list=document.getElementById('historyList'),h=history();list.innerHTML=h.length?'':'<p>Aucune visite enregistrée.</p>';const t=document.getElementById('historyTemplate');h.forEach((item,i)=>{const n=t.content.cloneNode(true);n.querySelector('.h-farm').textContent=item.data.farm;n.querySelector('.h-meta').textContent=`${item.data.visitDate} · ${item.data.species}${item.data.category?' · '+item.data.category:''}`;n.querySelector('.h-title').textContent=item.hypotheses[0]?.title||'Analyse';n.querySelector('.h-open').onclick=()=>{switchScreen('analyse');renderResult(item)};n.querySelector('.h-delete').onclick=()=>{const a=history();a.splice(i,1);saveHistory(a)};list.appendChild(n)})}document.getElementById('clearHistoryBtn').onclick=()=>{if(confirm('Supprimer tout l’historique ?'))saveHistory([])};function switchScreen(name){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('active',t.dataset.screen===name));document.getElementById(`screen-${name}`).classList.add('active');if(name==='history')renderHistory();scrollTo(0,0)}document.querySelectorAll('.tab').forEach(t=>t.onclick=()=>switchScreen(t.dataset.screen));window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBtn').classList.remove('hidden')});document.getElementById('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));renderHistory();
